#ifndef PRESSUREVOLUME_VOLUMEPRESSURECHANGEINPRESSUREVOLUME_H
#define PRESSUREVOLUME_VOLUMEPRESSURECHANGEINPRESSUREVOLUME_H

#include "SCUBACalculator.h"

extern "C" CALCULATORS_EXPORT CSCUBACalculator *instantiateCalculator();

#endif
